name: Deploy to GitHub Pages

on:
  push: 
    branches: main

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up BunJS
        uses: oven-sh/setup-bun@v2
    
      - name: Install dependencies
        run: bun install

      - name: Build the app
        env:
          BASE_PATH: /svelte-counter
        run: bun run build

      - name: Upload artifacts 
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment: 
      name: gitHub-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4

      
      